# Generated by Django 3.1.6 on 2022-07-28 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, max_length=512, null=True, upload_to='staticfiles/assets/images/articles/'),
        ),
    ]
