# Generated by Django 3.1.6 on 2022-07-28 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='filter',
            field=models.CharField(blank=True, choices=[('FILTER1', 'Collège'), ('FILTER2', 'Lycée'), ('FILTER3', 'Université'), ('FILTER4', 'Default')], default='FILTER4', max_length=265, null=True),
        ),
    ]
