# Generated by Django 3.1.6 on 2022-07-28 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0012_auto_20220728_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
