# Generated by Django 3.1.6 on 2022-07-28 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resultat', '0013_auto_20210522_0331'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResulatSA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('pourcentage_log', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': "Secteurs d'activités",
                'ordering': ['id'],
            },
        ),
        migrations.RemoveField(
            model_name='resultat',
            name='creatif',
        ),
        migrations.RemoveField(
            model_name='resultat',
            name='creatifDesc',
        ),
        migrations.RemoveField(
            model_name='resultat',
            name='entreprenant',
        ),
        migrations.RemoveField(
            model_name='resultat',
            name='entreprenantDesc',
        ),
        migrations.RemoveField(
            model_name='resultat',
            name='investigateur',
        ),
        migrations.RemoveField(
            model_name='resultat',
            name='investigateurDesc',
        ),
        migrations.RemoveField(
            model_name='resultat',
            name='methodique',
        ),
        migrations.RemoveField(
            model_name='resultat',
            name='methodiqueDesc',
        ),
        migrations.RemoveField(
            model_name='resultat',
            name='pratique',
        ),
        migrations.RemoveField(
            model_name='resultat',
            name='pratiqueDesc',
        ),
        migrations.RemoveField(
            model_name='resultat',
            name='social',
        ),
        migrations.RemoveField(
            model_name='resultat',
            name='socialDesc',
        ),
        migrations.AddField(
            model_name='resultat',
            name='secteur_activites',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resultats', to='resultat.resulatsa'),
        ),
    ]
