# Generated by Django 3.1.6 on 2022-07-28 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultat', '0014_auto_20220728_1720'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Matières',
                'ordering': ['id'],
            },
        ),
        migrations.RemoveField(
            model_name='resulatmetier',
            name='pourcentage',
        ),
        migrations.RemoveField(
            model_name='resulatmetier',
            name='resultat_metier',
        ),
        migrations.RemoveField(
            model_name='resultat',
            name='metier1',
        ),
        migrations.RemoveField(
            model_name='resultat',
            name='metier10',
        ),
        migrations.RemoveField(
            model_name='resultat',
            name='metier11',
        ),
        migrations.RemoveField(
            model_name='resultat',
            name='metier12',
        ),
        migrations.RemoveField(
            model_name='resultat',
            name='metier13',
        ),
        migrations.RemoveField(
            model_name='resultat',
            name='metier14',
        ),
        migrations.RemoveField(
            model_name='resultat',
            name='metier2',
        ),
        migrations.RemoveField(
            model_name='resultat',
            name='metier3',
        ),
        migrations.RemoveField(
            model_name='resultat',
            name='metier4',
        ),
        migrations.RemoveField(
            model_name='resultat',
            name='metier5',
        ),
        migrations.RemoveField(
            model_name='resultat',
            name='metier6',
        ),
        migrations.RemoveField(
            model_name='resultat',
            name='metier7',
        ),
        migrations.RemoveField(
            model_name='resultat',
            name='metier8',
        ),
        migrations.RemoveField(
            model_name='resultat',
            name='metier9',
        ),
        migrations.AddField(
            model_name='resulatmetier',
            name='level_algo',
            field=models.CharField(blank=True, choices=[('LEVEL1', 'Collège'), ('LEVEL2', 'Tronc Commun'), ('LEVEL3', '1ère année bac'), ('LEVEL4', 'Default')], default='LEVEL4', max_length=265, null=True),
        ),
        migrations.AddField(
            model_name='resulatmetier',
            name='metier1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='resulatmetier',
            name='metier2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='resulatmetier',
            name='metier3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='resulatmetier',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='resulatmetier',
            name='matieres',
            field=models.ManyToManyField(related_name='resultatmetiers', to='resultat.Matiere'),
        ),
    ]
